// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isqquleqerenslvpzubf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzcXF1bGVxZXJlbnNsdnB6dWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTIzODgsImV4cCI6MjA2NzQ4ODM4OH0.W19goxpqSbE2t0Hk8W-fQeEMJnKM4oQkCl6sthX9mso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});